# Workflow name
name: Build PDF


# Controls when the workflow will run
on: 
  # This is a reusable workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Podman Build Book
        run: podman run --name adocpdf --rm -v $(pwd):/tmp/coursebook:Z quay.io/tmichett/asciidocpdf:latest -a pdf-theme=/opt/asciidoc/themes/tm-gls-redhat-theme.yml Main.adoc

      - name: Commit and Add Book
        run: git add Main.pdf && git commit -m "Added new main.pdf" && git push
